version: '3'
services:
  django:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - react
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
